name: task5
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  http: ^1.3.0
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  flutter_native_splash: ^2.4.6
dev_dependencies:
  flutter_launcher_icons: "^0.14.3"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_icon.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  web: false
flutter:
  uses-material-design: true
  assets:
    - assets/images/